// .vitepress/theme/components/ChatWidget.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, provide } from 'vue'
import ChatWindow from './ChatWindow.vue'

const STORAGE_KEY = 'lh-chat-activated'
const activated = ref(false)
const open = ref(false)
const selectedText = ref('')
let lastGoodSelection = ''

provide('selectedText', selectedText)

const API_BASE = typeof window !== 'undefined'
  ? (window.location.hostname === 'localhost' ? 'http://localhost:3456' : 'http://43.130.41.3/Lighthouse')
  : ''

function grabSelection(): string {
  if (typeof window === 'undefined') return ''
  const sel = window.getSelection()
  if (!sel || sel.isCollapsed) return ''
  const text = sel.toString().trim()
  // Ignore selections inside our chat widget
  const anchor = sel.anchorNode?.parentElement
  if (anchor?.closest('.cw') || anchor?.closest('.cw-widget')) return ''
  if (text && text.length > 0 && text.length < 3000) return text
  return ''
}

function onMouseUp(e: MouseEvent) {
  // Only track selection from document area, ignore clicks inside chat
  const target = e.target as HTMLElement
  if (target?.closest('.cw') || target?.closest('.cw-widget') || target?.closest('.cw-fab')) return
  
  setTimeout(() => {
    const text = grabSelection()
    if (text) {
      selectedText.value = text
      lastGoodSelection = text
    }
  }, 10)
}

function onFabMouseDown() {
  // Snapshot current selection before click clears it
  const text = grabSelection()
  if (text) {
    selectedText.value = text
    lastGoodSelection = text
  } else if (lastGoodSelection) {
    // Restore last known good selection
    selectedText.value = lastGoodSelection
  }
}

onMounted(() => {
  if (typeof window !== 'undefined' && localStorage.getItem(STORAGE_KEY) === '1') {
    activated.value = true
  }
  document.addEventListener('keydown', handleGlobalKeydown, true)
  document.addEventListener('mouseup', onMouseUp)
})

onUnmounted(() => {
  document.removeEventListener('keydown', handleGlobalKeydown, true)
  document.removeEventListener('mouseup', onMouseUp)
})

async function handleGlobalKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
    const searchInput = document.querySelector('.VPLocalSearchBox input[type="search"], .VPLocalSearchBox input, [class*="DocSearch"] input') as HTMLInputElement | null
    if (!searchInput) return
    const val = searchInput.value.trim()
    if (!val) return
    e.preventDefault()
    e.stopPropagation()
    try {
      const res = await fetch(`${API_BASE}/api/verify`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ phrase: val })
      })
      const data = await res.json()
      if (data.ok) {
        activated.value = true
        localStorage.setItem(STORAGE_KEY, '1')
        searchInput.value = ''
        document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }))
        setTimeout(() => { open.value = true }, 300)
      }
    } catch (err) {
      console.warn('[LH Chat] verify failed:', err)
    }
  }
}
</script>

<template>
  <ClientOnly>
    <div v-if="activated" class="cw-widget">
      <ChatWindow :visible="open" @close="open = false" />
      <button
        class="cw-fab"
        :class="{ open }"
        @mousedown.prevent="onFabMouseDown"
        @click="open = !open"
        aria-label="打开助手"
      >
        <Transition name="cw-fab-icon" mode="out-in">
          <svg v-if="!open" key="icon" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6">
            <path d="M12 3L9.5 11h5L12 3z"/>
            <rect x="10.5" y="11" width="3" height="8" rx=".8"/>
            <path d="M8.5 21h7" stroke-linecap="round"/>
            <circle cx="12" cy="6" r=".8" fill="currentColor" stroke="none"/>
            <path d="M12 1.5V.5M15 3.5l.7-.7M17 6.5h1M9 3.5l-.7-.7M7 6.5H6" stroke-width="1.2" stroke-linecap="round" opacity=".5"/>
          </svg>
          <svg v-else key="close" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round">
            <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
          </svg>
        </Transition>
        <span v-if="!open && selectedText" class="cw-fab-dot" />
      </button>
    </div>
  </ClientOnly>
</template>

<style scoped>
.cw-widget { position: fixed; bottom: 0; right: 0; z-index: 1999; pointer-events: none; }
.cw-widget > * { pointer-events: auto; }
.cw-fab {
  position: fixed; bottom: 24px; right: 24px; width: 52px; height: 52px; border-radius: 16px;
  border: 1px solid var(--vp-c-divider); background: var(--vp-c-bg); color: var(--vp-c-text-1);
  cursor: pointer; display: flex; align-items: center; justify-content: center;
  z-index: 2001; transition: all .2s cubic-bezier(.4,0,.2,1);
  box-shadow: 0 0 0 1px rgba(0,0,0,.03), 0 1px 3px rgba(0,0,0,.06), 0 6px 16px rgba(0,0,0,.08);
}
.dark .cw-fab { box-shadow: 0 0 0 1px rgba(255,255,255,.06), 0 1px 3px rgba(0,0,0,.2), 0 6px 16px rgba(0,0,0,.3); }
.cw-fab:hover { transform: scale(1.05); }
.cw-fab:active { transform: scale(.97); }
.cw-fab.open { background: var(--vp-c-text-1); color: var(--vp-c-bg); border-color: var(--vp-c-text-1); border-radius: 14px; }
.cw-fab-dot {
  position: absolute; top: -3px; right: -3px; width: 10px; height: 10px; border-radius: 50%;
  background: #34c759; border: 2px solid var(--vp-c-bg); animation: cwPulse 1.5s infinite;
}
@keyframes cwPulse { 0%, 100% { transform: scale(1); } 50% { transform: scale(1.2); } }
.cw-fab-icon-enter-active, .cw-fab-icon-leave-active { transition: all .18s ease; }
.cw-fab-icon-enter-from { opacity: 0; transform: rotate(-90deg) scale(.5); }
.cw-fab-icon-leave-to { opacity: 0; transform: rotate(90deg) scale(.5); }
@media (max-width: 500px) { .cw-fab { bottom: 16px; right: 16px; width: 48px; height: 48px; border-radius: 14px; } }
</style>

// src/components/chat/ChatWidget.tsx
import { useState, useEffect, useRef, useCallback } from 'react';
import ChatWindow from './ChatWindow';
import './chat.css';

const STORAGE_KEY = 'lh-chat-activated';

function getApiBase(): string {
  if (typeof window === 'undefined') return '';
  return window.location.hostname === 'localhost'
    ? 'http://localhost:3456'
    : 'http://43.130.41.3/Lighthouse';
}

export default function ChatWidget() {
  const [activated, setActivated] = useState(false);
  const [open, setOpen] = useState(false);
  const [selectedText, setSelectedText] = useState('');
  const lastGoodSelection = useRef('');

  function grabSelection(): string {
    if (typeof window === 'undefined') return '';
    const sel = window.getSelection();
    if (!sel || sel.isCollapsed) return '';
    const text = sel.toString().trim();
    const anchor = sel.anchorNode?.parentElement;
    if (anchor?.closest('.cw') || anchor?.closest('.cw-widget')) return '';
    if (text && text.length > 0 && text.length < 3000) return text;
    return '';
  }

  const onMouseUp = useCallback((e: MouseEvent) => {
    const target = e.target as HTMLElement;
    if (target?.closest('.cw') || target?.closest('.cw-widget') || target?.closest('.cw-fab')) return;
    setTimeout(() => {
      const text = grabSelection();
      if (text) {
        setSelectedText(text);
        lastGoodSelection.current = text;
      }
    }, 10);
  }, []);

  const handleGlobalKeydown = useCallback(async (e: KeyboardEvent) => {
    if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
      const searchInput = document.querySelector(
        '.VPLocalSearchBox input[type="search"], .VPLocalSearchBox input, [class*="DocSearch"] input, .lh-search-input'
      ) as HTMLInputElement | null;
      if (!searchInput) return;
      const val = searchInput.value.trim();
      if (!val) return;
      e.preventDefault();
      e.stopPropagation();
      try {
        const res = await fetch(`${getApiBase()}/api/verify`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ phrase: val }),
        });
        const data = await res.json();
        if (data.ok) {
          setActivated(true);
          localStorage.setItem(STORAGE_KEY, '1');
          searchInput.value = '';
          document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
          setTimeout(() => setOpen(true), 300);
        }
      } catch (err) {
        console.warn('[LH Chat] verify failed:', err);
      }
    }
  }, []);

  useEffect(() => {
    if (localStorage.getItem(STORAGE_KEY) === '1') {
      setActivated(true);
    }
    document.addEventListener('keydown', handleGlobalKeydown, true);
    document.addEventListener('mouseup', onMouseUp);
    return () => {
      document.removeEventListener('keydown', handleGlobalKeydown, true);
      document.removeEventListener('mouseup', onMouseUp);
    };
  }, [handleGlobalKeydown, onMouseUp]);

  function onFabMouseDown() {
    const text = grabSelection();
    if (text) {
      setSelectedText(text);
      lastGoodSelection.current = text;
    } else if (lastGoodSelection.current) {
      setSelectedText(lastGoodSelection.current);
    }
  }

  if (!activated) return null;

  return (
    <div className="cw-widget">
      <ChatWindow
        visible={open}
        onClose={() => setOpen(false)}
        selectedText={selectedText}
        onClearSelection={() => setSelectedText('')}
      />
      <button
        className={`cw-fab ${open ? 'open' : ''}`}
        onMouseDown={(e) => { e.preventDefault(); onFabMouseDown(); }}
        onClick={() => setOpen(v => !v)}
        aria-label="打开助手"
      >
        {!open ? (
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6">
            <path d="M12 3L9.5 11h5L12 3z"/>
            <rect x="10.5" y="11" width="3" height="8" rx=".8"/>
            <path d="M8.5 21h7" strokeLinecap="round"/>
            <circle cx="12" cy="6" r=".8" fill="currentColor" stroke="none"/>
            <path d="M12 1.5V.5M15 3.5l.7-.7M17 6.5h1M9 3.5l-.7-.7M7 6.5H6" strokeWidth="1.2" strokeLinecap="round" opacity=".5"/>
          </svg>
        ) : (
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round">
            <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
          </svg>
        )}
        {!open && selectedText && <span className="cw-fab-dot" />}
      </button>
    </div>
  );
}
